version: '3'
services:
  db:
    build: ./db
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    links:
      - db
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
    links:
      - db
